const activityImages = {
  commute: require('../../assets/images/mood/commute.png'),
  exam: require('../../assets/images/mood/exam.png'),
  homework: require('../../assets/images/mood/homework.png'),
  project: require('../../assets/images/mood/project.png'),
  study: require('../../assets/images/mood/study.png'),
  read: require('../../assets/images/mood/read.png'),
  extracurricular: require('../../assets/images/mood/extraCurricularActivities.png'),
  'household-chores': require('../../assets/images/mood/householdChores.png'),
  relax: require('../../assets/images/mood/relax.png'),
  'watch-movie': require('../../assets/images/mood/watchMovie.png'),
  'listen-music': require('../../assets/images/mood/listenToMusic.png'),
  gaming: require('../../assets/images/mood/gaming.png'),
  'browse-internet': require('../../assets/images/mood/browseInternet.png'),
  shopping: require('../../assets/images/mood/shopping.png'),
  travel: require('../../assets/images/mood/travel.png'),
  alone: require('../../assets/images/mood/alone.png'),
  friends: require('../../assets/images/mood/friend.png'),
  family: require('../../assets/images/mood/family.png'),
  classmates: require('../../assets/images/mood/classmate.png'),
  relationship: require('../../assets/images/mood/relationship.png'),
  online: require('../../assets/images/mood/onlineInteraction.png'),
  pet: require('../../assets/images/mood/pet.png'),
  jog: require('../../assets/images/mood/jog.png'),
  walk: require('../../assets/images/mood/walk.png'),
  exercise: require('../../assets/images/mood/exercise.png'),
  meditate: require('../../assets/images/mood/meditate.png'),
  'eat-healthy': require('../../assets/images/mood/eatHealthy.png'),
  'no-physical': require('../../assets/images/mood/noPhysicalActivity.png'),
  'eat-unhealthy': require('../../assets/images/mood/eatUnhealthy.png')
};

export default activityImages;